Repository pimcore/skeleton, pull requests merged in 2022-08, with the labels that each got.

#108 Use compose v2
  .github/workflows/pimcore-skeleton.yml
Labels: enhancement

#114 parameters.secret should be longer -> causing issues with JWT library
  config/services.yaml
Labels: bug

#110 Add .m4a to nginx asset whitelist
  .docker/nginx.conf
Labels: task
