Repository pimcore/skeleton, pull requests merged in 2024-04, with the labels that each got.

#188 Add cs fixer workflow
  .github/workflows/php-cs-fixer.yaml
  src/Controller/DefaultController.php
Labels: Improvement

#187 Add RabbitMQ to docker-compose.yaml (#186)
  .docker/messenger.yaml
  composer.json
  docker-compose.yaml
Labels: Pimcore:ToDo

#191 Update SECURITY.md
  SECURITY.md
Labels: Task
